### ISSUE TITLE
Error during id_global_assignment

### ISSUE THREAD

**Issue by filipetrocadoferreira** [cheind/py-motmetrics#9]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1790, in _validate_key
    error()
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [nan] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 96, in <module>
    main(args)
  File "evaluate.py", line 86, in main
    summary = mh.compute(acc, metrics=[ 'id_global_assignment'],  name='acc')
  File "/usr/local/lib/python3.5/dist-packages/motmetrics/metrics.py", line 142, in compute
    cache[mname] = self._compute(df_map, mname, cache, parent='summarize')            
  File "/usr/local/lib/python3.5/dist-packages/motmetrics/metrics.py", line 205, in _compute
    return minfo['fnc'](df_map, *vals)
  File "/usr/local/lib/python3.5/dist-packages/motmetrics/metrics.py", line 335, in id_global_assignment
    df_o = df.loc[o, 'D'].dropna()
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 870, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 998, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1911, in _getitem_axis
    self._validate_key(key, axis)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1798, in _validate_key
    error()
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [nan] is not in the [index]'

```

**Comment by cheind** [comment]
@filipetrocadoferreira could you provide a minimal working example that reproduces the error?

**Comment by longcw** [comment]
@cheind I got the same error when running the `example.py` with pandas 0.23.0 
https://github.com/cheind/py-motmetrics/blob/v1.1.2/motmetrics/apps/example.py
