### ISSUE TITLE
"xmltodict" is missing in file "environment.yml"

### ISSUE THREAD

**Issue by ocanevet** [cheind/py-motmetrics#99]
When using the code only in the conda environment, running `python -m motmetrics.apps.eval_motchallenge --help` yields

```
Traceback (most recent call last):
  File "[...]/envs/motmetrics-env/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "[...]/envs/motmetrics-env/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "[...]/py-motmetrics/motmetrics/__init__.py", line 28, in <module>
    from motmetrics import io
  File "[...]/py-motmetrics/motmetrics/io.py", line 20, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
```

**Comment by cheind** [comment]
Ok thanks. I think, we haven't maintained the environment file. Maybe we should remove it infavor of the more up to date requirements.txt
